"use client";
import React, { useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Routes
import { sidebarCategories } from "@/data/routes";

// Components
import { Sidebar, Navbar } from "@/components/advanced";

// Styles
import Style from "./layout.module.css";
import "@/assets/css/index.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <html lang="en">
      <head></head>
      <body>
        <div className={Style.mainLayout}>
          <div className={menuOpen ? Style.sideBarOpen : Style.sideBar}>
            <Sidebar
              sidebarIsOpen={menuOpen}
              setSidebarIsOpen={setMenuOpen}
              sidebarCategories={sidebarCategories}
            />
          </div>
          <div className={Style.contentNavBar}>
            <Navbar sidebarIsOpen={menuOpen} setSidebarIsOpen={setMenuOpen} />
            <div className={Style.outlet}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
